import {
  Utensils,
  Beer,
  Salad,
  Sandwich,
  Pizza,
  Soup,
  Flame,
  Beef,
  WheatOff,
  ChefHat,
  UtensilsCrossed,
  Carrot,
  Cookie,
  Coffee,
  IceCream,
  CupSoda,
} from "lucide-react";

export const iconMap: Record<string, React.FC<{ className?: string }>> = {
  entradas: Utensils,
  picadas: Beer,
  ensaladas: Salad,
  sandwich: Sandwich,
  pizzas: Pizza,
  pastas: Soup,
  wok: Flame,
  hamburguesas: Beef,
  sintacc: WheatOff,
  minutas: ChefHat,
  platos: UtensilsCrossed,
  guarniciones: Carrot,
  tartas: Cookie,
  cafe: Coffee,
  postres: IceCream,
  bebidas: CupSoda,
};
